<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInstanceConfiguration" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="contents"  upperBound="-1"  eType="#//InstanceConfigContents"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterInstancePortRef" eSuperTypes="#//InstancePortRef #//PortRef ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="instance"  upperBound="1"  eType="#//ComponentInstance"  />
	<eStructuralFeatures xsi:type="ecore:EReference" name="port"  upperBound="1"  eType="#//Port"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="#//IArgumentLike #//IControlledNamedConcept #//IIdentifierNamedConcept #//INamedConcept #//ITyped ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentRef" eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="arg"  upperBound="1"  eType="#//IArgumentLike"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//ITypeContainingType #//Type ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector" eSuperTypes="#//InstanceConfigContents ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="source"  upperBound="1"  eType="#//InstancePortRef"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="target"  upperBound="1"  eType="#//InstancePortRef"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentExpr" eSuperTypes="#//BinaryExpression #//Expression ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicComponent" eSuperTypes="#//Component #//IIdentifierNamedConcept #//IModuleContent #//INamedConcept ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="contents"  upperBound="-1"  eType="#//IComponentContent"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryArithmeticExpression" abstract="true"  eSuperTypes="#//BinaryExpression #//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="left"  upperBound="1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="right"  upperBound="1"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryComparisonExpression" abstract="true"  eSuperTypes="#//BinaryExpression #//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="left"  upperBound="1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="right"  upperBound="1"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true"  eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="left"  upperBound="1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="right"  upperBound="1"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOrderedComparisonExpression" abstract="true"  eSuperTypes="#//BinaryComparisonExpression #//BinaryExpression #//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="left"  upperBound="1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="right"  upperBound="1"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClientServerInterface" eSuperTypes="#//IIdentifierNamedConcept #//IModuleContent #//INamedConcept #//Interface ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="contents"  upperBound="-1"  eType="#//ICSInterfaceContents"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//IModuleContent #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept #//InstanceConfigContents ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="component"  upperBound="1"  eType="#//Component"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executable" eSuperTypes="#//IComponentContent #//IFunctionLike #//IIdentifierNamedConcept #//INamedConcept #//ITyped ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="trigger"  eType="#//RunnableTrigger"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="body"  eType="#//StatementList"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteTestExpression" eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="tests"  upperBound="-1"  eType="#//ICanBeExecutedAsTest"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//Statement ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="expr"  upperBound="1"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//FunctionSignature #//IFunctionLike #//IIdentifierNamedConcept #//IModuleContent #//INamedConcept #//ITyped ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="body"  upperBound="1"  eType="#//StatementList"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionSignature" abstract="true"  eSuperTypes="#//IFunctionLike #//IIdentifierNamedConcept #//IModuleContent #//INamedConcept #//ITyped ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="arguments"  upperBound="-1"  eType="#//IArgumentLike"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="type"  upperBound="1"  eType="#//Type"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterEqualsExpression" eSuperTypes="#//BinaryComparisonExpression #//BinaryExpression #//BinaryOrderedComparisonExpression #//Expression ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IArgumentLike" abstract="true"  eSuperTypes="#//IControlledNamedConcept #//IIdentifierNamedConcept #//INamedConcept #//ITyped ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICSInterfaceContents" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICanBeExecutedAsTest" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IComponentContent" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IControlledNamedConcept" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFunctionLike" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept #//ITyped ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="arguments"  upperBound="-1"  eType="#//IArgumentLike"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="type"  upperBound="1"  eType="#//Type"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IIdentifierNamedConcept" abstract="true"  eSuperTypes="#//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IModuleContent" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IModuleContentContainer" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INamedConcept" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOperationTriggerLike" abstract="true" >
	<eStructuralFeatures xsi:type="ecore:EReference" name="providedPort"  upperBound="1"  eType="#//Port"  />
	<eStructuralFeatures xsi:type="ecore:EReference" name="calledOperation"  upperBound="1"  eType="#//Operation"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITypeContainingType" abstract="true" >
	<eStructuralFeatures xsi:type="ecore:EReference" name="baseType"  upperBound="1"  eType="#//Type"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITyped" abstract="true" >
	<eStructuralFeatures xsi:type="ecore:EReference" name="type"  upperBound="1"  eType="#//Type"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IVariableDeclaration" eSuperTypes="#//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationModule" eSuperTypes="#//IIdentifierNamedConcept #//IModuleContentContainer #//INamedConcept #//MbeddrModule ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitializeConfiguration" eSuperTypes="#//Statement ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="config"  upperBound="1"  eType="#//InstanceConfiguration"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceConfigContents" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceConfiguration" eSuperTypes="#//AbstractInstanceConfiguration #//IIdentifierNamedConcept #//IModuleContent #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstancePortRef" eSuperTypes="#//PortRef ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="instance"  upperBound="1"  eType="#//ComponentInstance"  />
	<eStructuralFeatures xsi:type="ecore:EReference" name="port"  upperBound="1"  eType="#//Port"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Int32Type" eSuperTypes="#//PrimitiveC99IntegralType #//PrimitiveType #//Type ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//IModuleContent #//INamedConcept ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceOperationCallExpr" abstract="true"  eSuperTypes="#//Expression #//UnaryExpression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="actuals"  upperBound="-1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="expression"  upperBound="1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="operation"  upperBound="1"  eType="#//Operation"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true"  eSuperTypes="#//Expression ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVarRef" eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="var"  upperBound="1"  eType="#//LocalVariableDeclaration"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableDeclaration" eSuperTypes="#//IControlledNamedConcept #//IIdentifierNamedConcept #//INamedConcept #//ITyped #//Statement ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="init"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MbeddrModule" abstract="true"  eSuperTypes="#//IIdentifierNamedConcept #//IModuleContentContainer #//INamedConcept ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="contents"  upperBound="-1"  eType="#//IModuleContent"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Expression #//Literal #//NumericLiteral ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericLiteral" abstract="true"  eSuperTypes="#//Expression #//Literal ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//ICSInterfaceContents #//IFunctionLike #//IIdentifierNamedConcept #//INamedConcept #//ITyped ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="parameters"  upperBound="-1"  eType="#//OperationParameter"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationParameter" eSuperTypes="#//IArgumentLike #//IControlledNamedConcept #//IIdentifierNamedConcept #//INamedConcept #//ITyped #//IVariableDeclaration ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTrigger" eSuperTypes="#//IOperationTriggerLike #//RunnableTrigger ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="providedPort"  upperBound="1"  eType="#//Port"  />
	<eStructuralFeatures xsi:type="ecore:EReference" name="calledOperation"  upperBound="1"  eType="#//Operation"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlusExpression" eSuperTypes="#//BinaryArithmeticExpression #//BinaryExpression #//Expression ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true"  eSuperTypes="#//IComponentContent #//IIdentifierNamedConcept #//INamedConcept ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="intf"  upperBound="1"  eType="#//Interface"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortAdapter" eSuperTypes="#//IIdentifierNamedConcept #//INamedConcept #//InstanceConfigContents ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="portRef"  upperBound="1"  eType="#//AdapterInstancePortRef"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortAdapterOpCallExpr" eSuperTypes="#//Expression #//InterfaceOperationCallExpr #//UnaryExpression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="operation"  upperBound="1"  eType="#//Operation"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortAdapterRefExpr" eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="portAdater"  upperBound="1"  eType="#//PortAdapter"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortRef" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortRefExpr" eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="port"  upperBound="1"  eType="#//Port"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveC99IntegralType" abstract="true"  eSuperTypes="#//PrimitiveType #//Type ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true"  eSuperTypes="#//Type ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//IComponentContent #//IIdentifierNamedConcept #//INamedConcept #//Port ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="intf"  upperBound="1"  eType="#//Interface"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//IComponentContent #//IIdentifierNamedConcept #//INamedConcept #//Port ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="intf"  upperBound="1"  eType="#//Interface"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPortOpCallExpr" eSuperTypes="#//Expression #//InterfaceOperationCallExpr #//UnaryExpression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="operation"  upperBound="1"  eType="#//Operation"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//Statement ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="expression"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunnableTrigger" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatementList" eSuperTypes="#//Statement ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="statements"  upperBound="-1"  eType="#//Statement"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Expression #//Literal ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//PrimitiveType #//Type ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase" eSuperTypes="#//IFunctionLike #//IIdentifierNamedConcept #//IModuleContent #//INamedConcept #//ITyped ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="body"  upperBound="1"  eType="#//StatementList"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCaseRef" eSuperTypes="#//ICanBeExecutedAsTest ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="testcase"  upperBound="1"  eType="#//TestCase"  />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" >
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true"  eSuperTypes="#//Expression ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="expression"  upperBound="1"  eType="#//Expression"  containment="true" />
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//PrimitiveType #//Type ">
</eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//Statement ">
	<eStructuralFeatures xsi:type="ecore:EReference" name="condition"  upperBound="1"  eType="#//Expression"  containment="true" />
	<eStructuralFeatures xsi:type="ecore:EReference" name="body"  upperBound="1"  eType="#//StatementList"  containment="true" />
</eClassifiers>
</ecore:EPackage>
